### ISSUE TITLE
RA/DEC fiits header possible issue

### ISSUE THREAD

**Issue by BorisE** [n0r1s123/CelestialSurveyor#2]
Runtime error on loading files through GUI.

Traceback (most recent call last):
  File "d:\python\CelestialSurveyor\backend\consuming_functions\load_headers.py", line 68, in load_headers_worker
    headers.append(load_header_fits(filename))
  File "d:\python\CelestialSurveyor\backend\consuming_functions\load_headers.py", line 216, in load_header_fits
    ra = Decimal(header['RA'])
  File "C:\Users\test\.conda\envs\astro\lib\site-packages\astropy\io\fits\header.py", line 170, in __getitem__
    card = self._cards[self._cardindex(key)]
  File "C:\Users\test\.conda\envs\astro\lib\site-packages\astropy\io\fits\header.py", line 1771, in _cardindex
    raise KeyError(f"Keyword {keyword!r} not found.")
KeyError: "Keyword 'RA' not found."

"It seems that the reason is that some astro capturing software puts coordinates into the FITS header under the tags 'OBJCTRA'/'OBJCTDEC' instead of 'RA'/'DEC'

**Comment by BorisE** [comment]
Example of FITS header values:
```
OBJECT		=	M2
OBJCTRA		=	21 33 27.0		
OBJCTDEC	=	-00 49 24.0		
OBJCTALT	=	44.2930		/	Nominal altitude of center of image
OBJCTAZ		=	173.5234	/	Nominal azimuth of center of image
OBJCTHA		=	-0.3088		/	Nominal hour angle of center of image

```

**Comment by n0r1s123** [comment]
Working on this
